FROM joshendriks/rpimatic1:0.0.1

# Install pimatic modules
RUN cd /home/pimatic-app && npm install pimatic-homeduino pimatic-mqtt

COPY config.rfslave.json /home/pimatic-app/config.json

# Run pimatic once so that all coffeescripts are built and npm packages are downloaded
# and built
## Make sure that pimatic will exit when startup is completed
RUN cp /home/pimatic-app/node_modules/pimatic/startup.coffee /home/pimatic-app/node_modules/pimatic/startup.backup
RUN sed -i "s/initComplete = true/framework.destroy().then( -> exit(0) )/g" /home/pimatic-app/node_modules/pimatic/startup.coffee
## Run pimatic
RUN cd / && pimatic.js
## Restore startup.coffee and remove it from compiled cache
RUN rm /home/pimatic-app/node_modules/pimatic/startup.coffee
RUN mv /home/pimatic-app/node_modules/pimatic/startup.backup /home/pimatic-app/node_modules/pimatic/startup.coffee
RUN rm /home/pimatic-app/node_modules/pimatic/.js/startup.*

# Run pimatic.js at start of the container
ENTRYPOINT ["pimatic.js"]

